# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - Python-Sched-Analytics

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      
      - name: Azure Login
        uses: azure/login@v2 # Updated to v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7450a932-75f2-4733-af66-568bdb474ebf }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6b8edcc8-cbde-4cf1-b1cd-49c91f45ab77 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8e4dd1dd-06d7-47ec-8387-da9fbd6fd437 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3 # Updated to v3 
        id: deploy-to-webapp
        with:
          app-name: 'Python-Sched-Analytics'
          slot-name: 'production'
          